# Interactive, log-in shell.

# generated by Git for Windows
[ -f ~/.profile ] && . ~/.profile
[ -f ~/.bashrc ]  && . ~/.bashrc

# This file really just loads .profile or .bashrc.
# Anything else can go in .bashrc.
